import { describe, expect, it } from 'vitest';
import { buildAfterWarpScript, getInterpolatedVariableNames, getWarpVariableDrafts, hasAfterWarpLabel } from '@/lib/warpAfterWarp';

describe('warpAfterWarp helpers', () => {
  it('collects only default variables in a stable order', () => {
    const drafts = getWarpVariableDrafts(new Map([
      ['score', { name: 'score', type: 'default', initialValue: '0', definedInBlockId: 'b1', line: 1 }],
      ['player_name', { name: 'player_name', type: 'define', initialValue: '"Player"', definedInBlockId: 'b1', line: 2 }],
      ['chapter', { name: 'chapter', type: 'default', initialValue: '1', definedInBlockId: 'b1', line: 3 }],
    ]), []);

    expect(drafts).toEqual([
      { name: 'chapter', value: '1', source: 'default' },
      { name: 'score', value: '0', source: 'default' },
    ]);
  });

  it('collects interpolated variables and assigns default_<name> values', () => {
    const drafts = getWarpVariableDrafts(new Map(), [
      { id: 's1', sourceText: 'Hello [mc_name]!', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
      { id: 's2', sourceText: 'Score: [points]', blockId: 'b1', filePath: 'game/script.rpy', line: 2, labelScope: null, characterTag: null, type: 'narration' },
    ]);

    expect(drafts).toEqual([
      { name: 'mc_name', value: 'default_mc_name', source: 'interpolated' },
      { name: 'points', value: 'default_points', source: 'interpolated' },
    ]);
  });

  it('extracts interpolated variable names from text expressions', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'Hello [mc_name]! [points:.2f]', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
    ])).toEqual(['mc_name', 'points']);
  });

  it('ignores config and ui files when scanning for interpolated variables', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'Version [config.version]', blockId: 'b1', filePath: 'game/screens.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
      { id: 's2', sourceText: 'Style [config.name]', blockId: 'b2', filePath: 'game/options.rpy', line: 2, labelScope: null, characterTag: null, type: 'narration' },
      { id: 's3', sourceText: 'Hello [mc_name]', blockId: 'b3', filePath: 'game/scenes/stage1/stage1_evening.rpy', line: 3, labelScope: null, characterTag: null, type: 'dialogue' },
    ])).toEqual(['mc_name']);
  });

  it('detects an actual after_warp label only when present', () => {
    expect(hasAfterWarpLabel({
      after_warp: { blockId: 'b1', label: 'after_warp', line: 12, column: 1, type: 'label' },
    })).toBe(true);

    expect(hasAfterWarpLabel({
      after_warp: { blockId: 'b1', label: 'after_warp', line: 12, column: 1, type: 'menu' },
    })).toBe(false);

    expect(hasAfterWarpLabel({})).toBe(false);
  });

  it('builds a temporary after_warp script with optional fallback label', () => {
    expect(buildAfterWarpScript([
      { name: 'score', value: '10' },
      { name: 'player_name', value: '"Debug"' },
      { name: 'mc_name', value: 'default_mc_name', source: 'interpolated' },
    ], true)).toBe(
      [
        '# Generated by Vangard Studio for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        'label after_warp:',
        '    $ score = 10',
        '    $ player_name = "Debug"',
        '    $ mc_name = "default_mc_name"',
        '    return',
        '',
      ].join('\n'),
    );
  });

  it('quotes plain text warp values while preserving expressions', () => {
    expect(buildAfterWarpScript([
      { name: 'mc_name', value: 'Alex', source: 'interpolated' },
      { name: 'chapter', value: 'persistent.chapter', source: 'default' },
    ], true)).toBe(
      [
        '# Generated by Vangard Studio for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        'label after_warp:',
        '    $ mc_name = "Alex"',
        '    $ chapter = persistent.chapter',
        '    return',
        '',
      ].join('\n'),
    );
  });

  it('builds an empty after_warp label when no variables are provided', () => {
    expect(buildAfterWarpScript([], true)).toBe(
      [
        '# Generated by Vangard Studio for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        'label after_warp:',
        '    return',
        '',
      ].join('\n'),
    );
  });

  it('omits the after_warp label when includeAfterWarpLabel is false and no variables exist', () => {
    expect(buildAfterWarpScript([], false)).toBe(
      '# Generated by Vangard Studio for temporary warp overrides.\n# This file is removed automatically after the game stops.\n',
    );
  });

  it('adds a disabled-overrides comment when variables exist but the project owns after_warp', () => {
    expect(buildAfterWarpScript([{ name: 'score', value: '10', source: 'default' }], false)).toBe(
      [
        '# Generated by Vangard Studio for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        '# Project already defines after_warp; keep overrides disabled to avoid duplicate labels.',
        '',
      ].join('\n'),
    );
  });

  it('preserves already-quoted string values', () => {
    const result = buildAfterWarpScript([{ name: 'name', value: '"Alice"', source: 'default' }], true);
    expect(result).toContain('    $ name = "Alice"');
  });

  it('preserves Python special literals True, False, and None without quoting', () => {
    const result = buildAfterWarpScript([
      { name: 'flag', value: 'True', source: 'default' },
      { name: 'active', value: 'False', source: 'default' },
      { name: 'data', value: 'None', source: 'default' },
    ], true);
    expect(result).toContain('    $ flag = True');
    expect(result).toContain('    $ active = False');
    expect(result).toContain('    $ data = None');
  });

  it('preserves list literal values without quoting', () => {
    const result = buildAfterWarpScript([{ name: 'items', value: '[1, 2, 3]', source: 'default' }], true);
    expect(result).toContain('    $ items = [1, 2, 3]');
  });

  it('preserves dot-access expressions without quoting', () => {
    const result = buildAfterWarpScript([{ name: 'hi_score', value: 'persistent.hi_score', source: 'default' }], true);
    expect(result).toContain('    $ hi_score = persistent.hi_score');
  });

  it('converts an empty string value to an empty quoted string', () => {
    const result = buildAfterWarpScript([{ name: 'name', value: '', source: 'interpolated' }], true);
    expect(result).toContain('    $ name = ""');
  });

  it('preserves arithmetic expressions without quoting', () => {
    const result = buildAfterWarpScript([{ name: 'result', value: 'x + 1', source: 'default' }], true);
    expect(result).toContain('    $ result = x + 1');
  });

  it('extracts only the variable name from format-spec expressions like [score:.2f]', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'Score: [score:.2f]', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
    ])).toEqual(['score']);
  });

  it('ignores fully dot-qualified tokens inside interpolations', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'v[renpy.version_string]', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'narration' },
    ])).toEqual([]);
  });

  it('returns an empty array when the source text contains no interpolations', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'No interpolation here.', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'narration' },
    ])).toEqual([]);
  });

  it('returns an empty array when both variables and strings are empty', () => {
    expect(getWarpVariableDrafts(new Map(), [])).toEqual([]);
  });

  it('prefers the default variable value over the same name found via interpolation', () => {
    const drafts = getWarpVariableDrafts(
      new Map([['mc_name', { name: 'mc_name', type: 'default', initialValue: '"Player"', definedInBlockId: 'b1', line: 1 }]]),
      [{ id: 's1', sourceText: 'Hello [mc_name]!', blockId: 'b1', filePath: 'game/script.rpy', line: 2, labelScope: null, characterTag: null, type: 'dialogue' }],
    );
    expect(drafts).toEqual([{ name: 'mc_name', value: '"Player"', source: 'default' }]);
  });

  it('merges default and interpolated variables in alphabetical order', () => {
    const drafts = getWarpVariableDrafts(
      new Map([['score', { name: 'score', type: 'default', initialValue: '0', definedInBlockId: 'b1', line: 1 }]]),
      [{ id: 's1', sourceText: '[mc_name] has [score] points', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' }],
    );
    expect(drafts).toEqual([
      { name: 'mc_name', value: 'default_mc_name', source: 'interpolated' },
      { name: 'score', value: '0', source: 'default' },
    ]);
  });
});
