/**
 * @file colorPalettes.ts
 * @description Static color palette data for the ColorPickerPane.
 * Each palette contains an id, display label, and an array of PaletteColor entries.
 */

export interface PaletteColor {
    hex: string;
    name: string;
}

export interface ColorPalette {
    id: string;
    label: string;
    colors: PaletteColor[];
}

/** Ren'Py Standard — colors commonly used for dialogue text tags in visual novels */
const RENPY_STANDARD: ColorPalette = {
    id: 'renpy_standard',
    label: "Ren'Py Standard",
    colors: [
        { hex: '#FFFFFF', name: 'White' },
        { hex: '#F0F0F0', name: 'Off White' },
        { hex: '#D3D3D3', name: 'Light Gray' },
        { hex: '#A9A9A9', name: 'Dark Gray' },
        { hex: '#808080', name: 'Gray' },
        { hex: '#000000', name: 'Black' },
        { hex: '#FF0000', name: 'Red' },
        { hex: '#FF4444', name: 'Light Red' },
        { hex: '#FF8888', name: 'Salmon Red' },
        { hex: '#FF6347', name: 'Tomato' },
        { hex: '#DC143C', name: 'Crimson' },
        { hex: '#8B0000', name: 'Dark Red' },
        { hex: '#FF69B4', name: 'Hot Pink' },
        { hex: '#FFB6C1', name: 'Light Pink' },
        { hex: '#FF1493', name: 'Deep Pink' },
        { hex: '#FFA500', name: 'Orange' },
        { hex: '#FF8C00', name: 'Dark Orange' },
        { hex: '#FFD700', name: 'Gold' },
        { hex: '#FFFF00', name: 'Yellow' },
        { hex: '#ADFF2F', name: 'Green Yellow' },
        { hex: '#00FF00', name: 'Lime' },
        { hex: '#00C800', name: 'Bright Green' },
        { hex: '#008000', name: 'Green' },
        { hex: '#006400', name: 'Dark Green' },
        { hex: '#00FFFF', name: 'Cyan' },
        { hex: '#00CED1', name: 'Dark Turquoise' },
        { hex: '#20B2AA', name: 'Light Sea Green' },
        { hex: '#1E90FF', name: 'Dodger Blue' },
        { hex: '#4169E1', name: 'Royal Blue' },
        { hex: '#0000FF', name: 'Blue' },
        { hex: '#00008B', name: 'Dark Blue' },
        { hex: '#8A2BE2', name: 'Blue Violet' },
        { hex: '#9400D3', name: 'Dark Violet' },
        { hex: '#EE82EE', name: 'Violet' },
        { hex: '#DA70D6', name: 'Orchid' },
        { hex: '#C0C0C0', name: 'Silver' },
    ],
};

/** HTML Named Colors — CSS Level 1/2/3 named colors */
const HTML_NAMED: ColorPalette = {
    id: 'html_named',
    label: 'HTML Named',
    colors: [
        { hex: '#F0F8FF', name: 'AliceBlue' },
        { hex: '#FAEBD7', name: 'AntiqueWhite' },
        { hex: '#00FFFF', name: 'Aqua' },
        { hex: '#7FFFD4', name: 'Aquamarine' },
        { hex: '#F0FFFF', name: 'Azure' },
        { hex: '#F5F5DC', name: 'Beige' },
        { hex: '#FFE4C4', name: 'Bisque' },
        { hex: '#000000', name: 'Black' },
        { hex: '#FFEBCD', name: 'BlanchedAlmond' },
        { hex: '#0000FF', name: 'Blue' },
        { hex: '#8A2BE2', name: 'BlueViolet' },
        { hex: '#A52A2A', name: 'Brown' },
        { hex: '#DEB887', name: 'BurlyWood' },
        { hex: '#5F9EA0', name: 'CadetBlue' },
        { hex: '#7FFF00', name: 'Chartreuse' },
        { hex: '#D2691E', name: 'Chocolate' },
        { hex: '#FF7F50', name: 'Coral' },
        { hex: '#6495ED', name: 'CornflowerBlue' },
        { hex: '#FFF8DC', name: 'Cornsilk' },
        { hex: '#DC143C', name: 'Crimson' },
        { hex: '#00008B', name: 'DarkBlue' },
        { hex: '#008B8B', name: 'DarkCyan' },
        { hex: '#B8860B', name: 'DarkGoldenRod' },
        { hex: '#A9A9A9', name: 'DarkGray' },
        { hex: '#006400', name: 'DarkGreen' },
        { hex: '#BDB76B', name: 'DarkKhaki' },
        { hex: '#8B008B', name: 'DarkMagenta' },
        { hex: '#556B2F', name: 'DarkOliveGreen' },
        { hex: '#FF8C00', name: 'DarkOrange' },
        { hex: '#9932CC', name: 'DarkOrchid' },
        { hex: '#8B0000', name: 'DarkRed' },
        { hex: '#E9967A', name: 'DarkSalmon' },
        { hex: '#8FBC8F', name: 'DarkSeaGreen' },
        { hex: '#483D8B', name: 'DarkSlateBlue' },
        { hex: '#2F4F4F', name: 'DarkSlateGray' },
        { hex: '#00CED1', name: 'DarkTurquoise' },
        { hex: '#9400D3', name: 'DarkViolet' },
        { hex: '#FF1493', name: 'DeepPink' },
        { hex: '#00BFFF', name: 'DeepSkyBlue' },
        { hex: '#696969', name: 'DimGray' },
        { hex: '#1E90FF', name: 'DodgerBlue' },
        { hex: '#B22222', name: 'FireBrick' },
        { hex: '#FFFAF0', name: 'FloralWhite' },
        { hex: '#228B22', name: 'ForestGreen' },
        { hex: '#FF00FF', name: 'Fuchsia' },
        { hex: '#DCDCDC', name: 'Gainsboro' },
        { hex: '#F8F8FF', name: 'GhostWhite' },
        { hex: '#FFD700', name: 'Gold' },
        { hex: '#DAA520', name: 'GoldenRod' },
        { hex: '#808080', name: 'Gray' },
        { hex: '#008000', name: 'Green' },
        { hex: '#ADFF2F', name: 'GreenYellow' },
        { hex: '#F0FFF0', name: 'HoneyDew' },
        { hex: '#FF69B4', name: 'HotPink' },
        { hex: '#CD5C5C', name: 'IndianRed' },
        { hex: '#4B0082', name: 'Indigo' },
        { hex: '#FFFFF0', name: 'Ivory' },
        { hex: '#F0E68C', name: 'Khaki' },
        { hex: '#E6E6FA', name: 'Lavender' },
        { hex: '#FFF0F5', name: 'LavenderBlush' },
        { hex: '#7CFC00', name: 'LawnGreen' },
        { hex: '#FFFACD', name: 'LemonChiffon' },
        { hex: '#ADD8E6', name: 'LightBlue' },
        { hex: '#F08080', name: 'LightCoral' },
        { hex: '#E0FFFF', name: 'LightCyan' },
        { hex: '#90EE90', name: 'LightGreen' },
        { hex: '#D3D3D3', name: 'LightGray' },
        { hex: '#FFB6C1', name: 'LightPink' },
        { hex: '#FFA07A', name: 'LightSalmon' },
        { hex: '#20B2AA', name: 'LightSeaGreen' },
        { hex: '#87CEFA', name: 'LightSkyBlue' },
        { hex: '#778899', name: 'LightSlateGray' },
        { hex: '#B0C4DE', name: 'LightSteelBlue' },
        { hex: '#FFFFE0', name: 'LightYellow' },
        { hex: '#00FF00', name: 'Lime' },
        { hex: '#32CD32', name: 'LimeGreen' },
        { hex: '#FAF0E6', name: 'Linen' },
        { hex: '#FF00FF', name: 'Magenta' },
        { hex: '#800000', name: 'Maroon' },
        { hex: '#66CDAA', name: 'MediumAquaMarine' },
        { hex: '#0000CD', name: 'MediumBlue' },
        { hex: '#BA55D3', name: 'MediumOrchid' },
        { hex: '#9370DB', name: 'MediumPurple' },
        { hex: '#3CB371', name: 'MediumSeaGreen' },
        { hex: '#7B68EE', name: 'MediumSlateBlue' },
        { hex: '#00FA9A', name: 'MediumSpringGreen' },
        { hex: '#48D1CC', name: 'MediumTurquoise' },
        { hex: '#C71585', name: 'MediumVioletRed' },
        { hex: '#191970', name: 'MidnightBlue' },
        { hex: '#F5FFFA', name: 'MintCream' },
        { hex: '#FFE4E1', name: 'MistyRose' },
        { hex: '#FFDEAD', name: 'NavajoWhite' },
        { hex: '#808080', name: 'Olive' },
        { hex: '#6B8E23', name: 'OliveDrab' },
        { hex: '#FFA500', name: 'Orange' },
        { hex: '#FF4500', name: 'OrangeRed' },
        { hex: '#DA70D6', name: 'Orchid' },
        { hex: '#EEE8AA', name: 'PaleGoldenRod' },
        { hex: '#98FB98', name: 'PaleGreen' },
        { hex: '#AFEEEE', name: 'PaleTurquoise' },
        { hex: '#DB7093', name: 'PaleVioletRed' },
        { hex: '#FFDAB9', name: 'PeachPuff' },
        { hex: '#CD853F', name: 'Peru' },
        { hex: '#FFC0CB', name: 'Pink' },
        { hex: '#DDA0DD', name: 'Plum' },
        { hex: '#B0E0E6', name: 'PowderBlue' },
        { hex: '#800080', name: 'Purple' },
        { hex: '#FF0000', name: 'Red' },
        { hex: '#BC8F8F', name: 'RosyBrown' },
        { hex: '#4169E1', name: 'RoyalBlue' },
        { hex: '#8B4513', name: 'SaddleBrown' },
        { hex: '#FA8072', name: 'Salmon' },
        { hex: '#F4A460', name: 'SandyBrown' },
        { hex: '#2E8B57', name: 'SeaGreen' },
        { hex: '#FFF5EE', name: 'SeaShell' },
        { hex: '#A0522D', name: 'Sienna' },
        { hex: '#C0C0C0', name: 'Silver' },
        { hex: '#87CEEB', name: 'SkyBlue' },
        { hex: '#6A5ACD', name: 'SlateBlue' },
        { hex: '#708090', name: 'SlateGray' },
        { hex: '#00FF7F', name: 'SpringGreen' },
        { hex: '#4682B4', name: 'SteelBlue' },
        { hex: '#D2B48C', name: 'Tan' },
        { hex: '#008080', name: 'Teal' },
        { hex: '#D8BFD8', name: 'Thistle' },
        { hex: '#FF6347', name: 'Tomato' },
        { hex: '#40E0D0', name: 'Turquoise' },
        { hex: '#EE82EE', name: 'Violet' },
        { hex: '#F5DEB3', name: 'Wheat' },
        { hex: '#FFFFFF', name: 'White' },
        { hex: '#F5F5F5', name: 'WhiteSmoke' },
        { hex: '#FFFF00', name: 'Yellow' },
        { hex: '#9ACD32', name: 'YellowGreen' },
    ],
};

/** Material Design 500 — Google Material Design colors at 500 weight */
const MATERIAL_500: ColorPalette = {
    id: 'material_500',
    label: 'Material 500',
    colors: [
        { hex: '#F44336', name: 'Red 500' },
        { hex: '#E91E63', name: 'Pink 500' },
        { hex: '#9C27B0', name: 'Purple 500' },
        { hex: '#673AB7', name: 'Deep Purple 500' },
        { hex: '#3F51B5', name: 'Indigo 500' },
        { hex: '#2196F3', name: 'Blue 500' },
        { hex: '#03A9F4', name: 'Light Blue 500' },
        { hex: '#00BCD4', name: 'Cyan 500' },
        { hex: '#009688', name: 'Teal 500' },
        { hex: '#4CAF50', name: 'Green 500' },
        { hex: '#8BC34A', name: 'Light Green 500' },
        { hex: '#CDDC39', name: 'Lime 500' },
        { hex: '#FFEB3B', name: 'Yellow 500' },
        { hex: '#FFC107', name: 'Amber 500' },
        { hex: '#FF9800', name: 'Orange 500' },
        { hex: '#FF5722', name: 'Deep Orange 500' },
        { hex: '#795548', name: 'Brown 500' },
        { hex: '#9E9E9E', name: 'Grey 500' },
        { hex: '#607D8B', name: 'Blue Grey 500' },
        // 100 weights
        { hex: '#FFCDD2', name: 'Red 100' },
        { hex: '#F8BBD0', name: 'Pink 100' },
        { hex: '#E1BEE7', name: 'Purple 100' },
        { hex: '#D1C4E9', name: 'Deep Purple 100' },
        { hex: '#C5CAE9', name: 'Indigo 100' },
        { hex: '#BBDEFB', name: 'Blue 100' },
        { hex: '#B3E5FC', name: 'Light Blue 100' },
        { hex: '#B2EBF2', name: 'Cyan 100' },
        { hex: '#B2DFDB', name: 'Teal 100' },
        { hex: '#C8E6C9', name: 'Green 100' },
        { hex: '#DCEDC8', name: 'Light Green 100' },
        { hex: '#F0F4C3', name: 'Lime 100' },
        { hex: '#FFF9C4', name: 'Yellow 100' },
        { hex: '#FFECB3', name: 'Amber 100' },
        { hex: '#FFE0B2', name: 'Orange 100' },
        { hex: '#FBE9E7', name: 'Deep Orange 100' },
        // 900 weights
        { hex: '#B71C1C', name: 'Red 900' },
        { hex: '#880E4F', name: 'Pink 900' },
        { hex: '#4A148C', name: 'Purple 900' },
        { hex: '#311B92', name: 'Deep Purple 900' },
        { hex: '#1A237E', name: 'Indigo 900' },
        { hex: '#0D47A1', name: 'Blue 900' },
        { hex: '#01579B', name: 'Light Blue 900' },
        { hex: '#006064', name: 'Cyan 900' },
        { hex: '#004D40', name: 'Teal 900' },
        { hex: '#1B5E20', name: 'Green 900' },
        { hex: '#33691E', name: 'Light Green 900' },
        { hex: '#827717', name: 'Lime 900' },
        { hex: '#F57F17', name: 'Yellow 900' },
        { hex: '#FF6F00', name: 'Amber 900' },
        { hex: '#E65100', name: 'Orange 900' },
        { hex: '#BF360C', name: 'Deep Orange 900' },
    ],
};

/** Pastel — soft muted tones popular in visual novel UIs */
const PASTEL: ColorPalette = {
    id: 'pastel',
    label: 'Pastel',
    colors: [
        { hex: '#FFB3BA', name: 'Pastel Red' },
        { hex: '#FFDFBA', name: 'Pastel Orange' },
        { hex: '#FFFFBA', name: 'Pastel Yellow' },
        { hex: '#BAFFC9', name: 'Pastel Green' },
        { hex: '#BAE1FF', name: 'Pastel Blue' },
        { hex: '#E8BAFF', name: 'Pastel Violet' },
        { hex: '#FFC8DD', name: 'Pastel Pink' },
        { hex: '#BDE0FE', name: 'Pastel Sky' },
        { hex: '#A2D2FF', name: 'Pastel Cornflower' },
        { hex: '#CDB4DB', name: 'Pastel Lilac' },
        { hex: '#FFC8A2', name: 'Pastel Peach' },
        { hex: '#D4E157', name: 'Pastel Lime' },
        { hex: '#80DEEA', name: 'Pastel Cyan' },
        { hex: '#F48FB1', name: 'Pastel Rose' },
        { hex: '#CE93D8', name: 'Pastel Plum' },
        { hex: '#90CAF9', name: 'Pastel Periwinkle' },
        { hex: '#A5D6A7', name: 'Pastel Mint' },
        { hex: '#FFF9C4', name: 'Pastel Cream' },
        { hex: '#D7CCC8', name: 'Pastel Taupe' },
        { hex: '#B0BEC5', name: 'Pastel Slate' },
        { hex: '#FFE4E1', name: 'Misty Rose' },
        { hex: '#F0E6FF', name: 'Lavender Mist' },
        { hex: '#E6F4FF', name: 'Ice Blue' },
        { hex: '#E6FFE6', name: 'Mint Cream' },
        { hex: '#FFFDE7', name: 'Buttercup' },
        { hex: '#FBE9E7', name: 'Apricot' },
        { hex: '#F3E5F5', name: 'Orchid Tint' },
        { hex: '#E0F2F1', name: 'Seafoam Tint' },
        { hex: '#E8EAF6', name: 'Indigo Tint' },
        { hex: '#FCE4EC', name: 'Cherry Blossom' },
    ],
};

/** The ordered list of all built-in palettes. The 'project' palette is injected dynamically. */
export const BUILT_IN_PALETTES: ColorPalette[] = [
    RENPY_STANDARD,
    HTML_NAMED,
    MATERIAL_500,
    PASTEL,
];

/** Expand a 3-digit hex shorthand to 6-digit form. */
export function expandHex(hex: string): string {
    const trimmed = hex.replace(/^#/, '');
    if (trimmed.length === 3) {
        return '#' + trimmed.split('').map(c => c + c).join('');
    }
    return hex.toUpperCase().startsWith('#') ? hex.toUpperCase() : '#' + hex.toUpperCase();
}
