/**
 * @file ScreenLayoutComposer.tsx
 * @description WYSIWYG canvas editor for Ren'Py `screen` layouts.
 * Drag widgets from the palette onto the dark game canvas, drag to reposition,
 * drag corner handles to resize, double-click text to edit inline.
 * Hierarchy managed via the Layers panel. Code generated by `lib/screenCodeGenerator`.
 */
import React, { useState, useCallback, useRef, useEffect } from 'react';
import type { ScreenLayoutComposition, ScreenWidget, ScreenWidgetType } from '@/types';
import { generateScreenCode } from '@/lib/screenCodeGenerator';
import { createId } from '@/lib/createId';
import CodeActionButtons from './CodeActionButtons';
import type * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

interface ScreenLayoutComposerProps {
    composition: ScreenLayoutComposition;
    onCompositionChange: (value: React.SetStateAction<ScreenLayoutComposition>) => void;
    screenName: string;
    onRenameScreen: (newName: string) => void;
    labels: string[];
    isLocked?: boolean;
    isActive?: boolean;
    onDuplicate?: () => void;
    onGoToCode?: () => void;
    activeEditor?: monaco.editor.IStandaloneCodeEditor | null;
}

// ─── Icons ───────────────────────────────────────────────────────────────────
const Icon: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = 'w-5 h-5' }) => (
    <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className={className}>
        {children}
    </svg>
);

const WIDGET_ICONS: Record<ScreenWidgetType, React.ReactNode> = {
    vbox:        <Icon><rect x="3" y="2"  width="14" height="4" rx="1" fill="currentColor" opacity="0.9"/><rect x="3" y="8"  width="14" height="4" rx="1" fill="currentColor" opacity="0.6"/><rect x="3" y="14" width="14" height="4" rx="1" fill="currentColor" opacity="0.35"/></Icon>,
    hbox:        <Icon><rect x="2"  y="3" width="4" height="14" rx="1" fill="currentColor" opacity="0.9"/><rect x="8"  y="3" width="4" height="14" rx="1" fill="currentColor" opacity="0.6"/><rect x="14" y="3" width="4" height="14" rx="1" fill="currentColor" opacity="0.35"/></Icon>,
    frame:       <Icon><rect x="2" y="2" width="16" height="16" rx="2" stroke="currentColor" strokeWidth="2"/><rect x="5" y="5" width="10" height="10" rx="1" stroke="currentColor" strokeWidth="1" strokeDasharray="2 1.5" opacity="0.5"/></Icon>,
    text:        <Icon><path d="M4 4h12M10 4v12" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M7 16h6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity="0.5"/></Icon>,
    image:       <Icon><rect x="2" y="4" width="16" height="12" rx="2" stroke="currentColor" strokeWidth="1.5"/><circle cx="7" cy="8.5" r="1.5" fill="currentColor" opacity="0.7"/><path d="M2 13.5l4.5-4 3 3 2.5-2.5 6 4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.8"/></Icon>,
    textbutton:  <Icon><rect x="2" y="6" width="16" height="8" rx="3" stroke="currentColor" strokeWidth="1.5"/><path d="M6 10h8" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></Icon>,
    button:      <Icon><rect x="2" y="6" width="16" height="8" rx="3" stroke="currentColor" strokeWidth="1.5"/><circle cx="10" cy="10" r="2.5" fill="currentColor" opacity="0.4"/><circle cx="10" cy="10" r="1" fill="currentColor" opacity="0.8"/></Icon>,
    imagebutton: <Icon><rect x="2" y="3" width="16" height="10" rx="2" stroke="currentColor" strokeWidth="1.5"/><circle cx="6.5" cy="7" r="1.2" fill="currentColor" opacity="0.6"/><path d="M2 11l3.5-3 2.5 2 2-2 6 4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.7"/><rect x="6" y="14.5" width="8" height="3" rx="1.5" fill="currentColor" opacity="0.5"/></Icon>,
    bar:         <Icon><rect x="2" y="8"  width="16" height="4" rx="2" stroke="currentColor" strokeWidth="1.5"/><rect x="2" y="8"  width="10" height="4" rx="2" fill="currentColor" opacity="0.45"/><path d="M2 14h4M7 14h2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" opacity="0.4"/></Icon>,
    input:       <Icon><rect x="2" y="6" width="16" height="8" rx="2" stroke="currentColor" strokeWidth="1.5"/><path d="M5 10h5" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/><path d="M11 7.5v5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity="0.6"/></Icon>,
    null:        <Icon><path d="M3 10h2.5M8.5 10h3M14.5 10H17" stroke="currentColor" strokeWidth="2" strokeLinecap="round" opacity="0.5"/><path d="M3 6h14M3 14h14" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeDasharray="2 2" opacity="0.25"/></Icon>,
};

const WIDGET_ICON_COLORS: Record<ScreenWidgetType, string> = {
    vbox:        'text-blue-500   dark:text-blue-400',
    hbox:        'text-indigo-500 dark:text-indigo-400',
    frame:       'text-purple-500 dark:text-purple-400',
    text:        'text-gray-500   dark:text-gray-300',
    image:       'text-green-500  dark:text-green-400',
    textbutton:  'text-yellow-600 dark:text-yellow-400',
    button:      'text-orange-500 dark:text-orange-400',
    imagebutton: 'text-lime-600   dark:text-lime-400',
    bar:         'text-teal-500   dark:text-teal-400',
    input:       'text-pink-500   dark:text-pink-400',
    null:        'text-gray-400   dark:text-gray-500',
};

const WIDGET_TILE_COLORS: Record<ScreenWidgetType, string> = {
    vbox:        'bg-blue-50   dark:bg-blue-950  border-blue-200   dark:border-blue-800  hover:border-blue-400   dark:hover:border-blue-500',
    hbox:        'bg-indigo-50 dark:bg-indigo-950 border-indigo-200 dark:border-indigo-800 hover:border-indigo-400 dark:hover:border-indigo-500',
    frame:       'bg-purple-50 dark:bg-purple-950 border-purple-200 dark:border-purple-800 hover:border-purple-400 dark:hover:border-purple-500',
    text:        'bg-gray-50   dark:bg-gray-800  border-gray-200   dark:border-gray-600  hover:border-gray-400   dark:hover:border-gray-400',
    image:       'bg-green-50  dark:bg-green-950 border-green-200  dark:border-green-800 hover:border-green-400  dark:hover:border-green-500',
    textbutton:  'bg-yellow-50 dark:bg-yellow-950 border-yellow-200 dark:border-yellow-800 hover:border-yellow-400 dark:hover:border-yellow-500',
    button:      'bg-orange-50 dark:bg-orange-950 border-orange-200 dark:border-orange-800 hover:border-orange-400 dark:hover:border-orange-500',
    imagebutton: 'bg-lime-50   dark:bg-lime-950  border-lime-200   dark:border-lime-800  hover:border-lime-400   dark:hover:border-lime-500',
    bar:         'bg-teal-50   dark:bg-teal-950  border-teal-200   dark:border-teal-800  hover:border-teal-400   dark:hover:border-teal-500',
    input:       'bg-pink-50   dark:bg-pink-950  border-pink-200   dark:border-pink-800  hover:border-pink-400   dark:hover:border-pink-500',
    null:        'bg-gray-50   dark:bg-gray-900  border-gray-200   dark:border-gray-700  hover:border-gray-300   dark:hover:border-gray-500',
};

const WIDGET_LABELS: Record<ScreenWidgetType, string> = {
    vbox: 'Vertical Box', hbox: 'Horizontal Box', frame: 'Frame',
    text: 'Text', image: 'Image', textbutton: 'Text Button',
    button: 'Button', imagebutton: 'Image Button', bar: 'Bar',
    input: 'Input', null: 'Spacer',
};

const PALETTE_GROUPS: { label: string; icon: React.ReactNode; types: ScreenWidgetType[] }[] = [
    { label: 'Layout',      icon: <Icon className="w-3.5 h-3.5"><path d="M2 5h16M2 10h16M2 15h16" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></Icon>,          types: ['vbox', 'hbox', 'frame'] },
    { label: 'Display',     icon: <Icon className="w-3.5 h-3.5"><rect x="3" y="3" width="14" height="14" rx="2" stroke="currentColor" strokeWidth="1.5"/></Icon>,                  types: ['text', 'image'] },
    { label: 'Interactive', icon: <Icon className="w-3.5 h-3.5"><path d="M8 8l6 4-6 4V8z" fill="currentColor" opacity="0.8"/></Icon>,                                              types: ['textbutton', 'button', 'imagebutton'] },
    { label: 'Other',       icon: <Icon className="w-3.5 h-3.5"><circle cx="5" cy="10" r="1.5" fill="currentColor" opacity="0.6"/><circle cx="10" cy="10" r="1.5" fill="currentColor" opacity="0.6"/><circle cx="15" cy="10" r="1.5" fill="currentColor" opacity="0.6"/></Icon>, types: ['bar', 'input', 'null'] },
];

// ─── Types ────────────────────────────────────────────────────────────────────
type DropPosition = 'before' | 'after' | 'inside';
interface DropTarget { id: string; position: DropPosition; }
interface TreeDragState { draggingId: string | null; dropTarget: DropTarget | null; }
interface TreeDragCallbacks {
    onDragStart: (id: string) => void;
    onDragOver: (id: string, position: DropPosition) => void;
    onDrop: () => void;
    onDragEnd: () => void;
}

type ResizeHandleDir = 'nw' | 'ne' | 'sw' | 'se';

interface CanvasDragState {
    widgetId: string;
    offsetX: number; // pointer offset from widget top-left, in game pixels
    offsetY: number;
}

interface ResizeDragState {
    widgetId: string;
    handle: ResizeHandleDir;
    startPointerX: number; // in game pixels
    startPointerY: number;
    startX: number;
    startY: number;
    startW: number;
    startH: number;
}

// Shared context threaded into every CanvasWidget in the tree.
interface CanvasCtxValue {
    selectedId: string | null;
    inlineEditId: string | null;
    inlineEditText: string;
    containerDropTarget: string | null;
    gameWidth: number;
    gameHeight: number;
    onSelect: (id: string) => void;
    onWidgetPointerDown: (e: React.PointerEvent<HTMLDivElement>, id: string) => void;
    onResizePointerDown: (e: React.PointerEvent<HTMLDivElement>, id: string, handle: ResizeHandleDir) => void;
    onInlineEditChange: (text: string) => void;
    onInlineEditCommit: () => void;
    onInlineEditStart: (widget: ScreenWidget) => void;
    onUpdateWidget: (id: string, fn: (w: ScreenWidget) => ScreenWidget) => void;
    onContainerDragOver: (e: React.DragEvent<HTMLDivElement>, id: string) => void;
    onContainerDrop: (e: React.DragEvent<HTMLDivElement>, containerId: string) => void;
    onContainerDragLeave: () => void;
}

const CanvasCtx = React.createContext<CanvasCtxValue>(null!);

// ─── Widget helpers ───────────────────────────────────────────────────────────
const CONTAINER_TYPES: ScreenWidgetType[] = ['vbox', 'hbox', 'frame', 'button'];
function isContainer(w: ScreenWidget) { return CONTAINER_TYPES.includes(w.type); }

function makeWidget(type: ScreenWidgetType): ScreenWidget {
    const id = createId('widget');
    const base: ScreenWidget = { id, type };
    if (type === 'text')        return { ...base, text: 'Text' };
    if (type === 'textbutton')  return { ...base, text: 'Button', action: 'Return()' };
    if (type === 'button')      return { ...base, action: 'Return()', children: [] };
    if (type === 'imagebutton') return { ...base, imagePath: '', action: 'Return()' };
    if (type === 'vbox' || type === 'hbox' || type === 'frame') return { ...base, children: [] };
    return base;
}

// Convert a widget's position properties to absolute game-pixel coords for canvas display.
function getWidgetDisplayPos(w: ScreenWidget, gw: number, gh: number): { x: number; y: number } {
    return {
        x: w.xpos !== undefined ? w.xpos : w.xalign !== undefined ? Math.round(w.xalign * gw) : 0,
        y: w.ypos !== undefined ? w.ypos : w.yalign !== undefined ? Math.round(w.yalign * gh) : 0,
    };
}

// Map a client pointer position into game-pixel coordinates relative to the canvas element.
function clientToGame(clientX: number, clientY: number, canvas: HTMLDivElement, gw: number, gh: number) {
    const r = canvas.getBoundingClientRect();
    return {
        x: Math.round(((clientX - r.left) / r.width)  * gw),
        y: Math.round(((clientY - r.top)  / r.height) * gh),
    };
}

function findWidget(widgets: ScreenWidget[], id: string): ScreenWidget | null {
    for (const w of widgets) {
        if (w.id === id) return w;
        if (w.children) { const f = findWidget(w.children, id); if (f) return f; }
    }
    return null;
}

function addToContainer(widgets: ScreenWidget[], containerId: string, nw: ScreenWidget): ScreenWidget[] {
    return widgets.map(w => {
        if (w.id === containerId && w.children !== undefined) return { ...w, children: [...w.children, nw] };
        if (w.children) return { ...w, children: addToContainer(w.children, containerId, nw) };
        return w;
    });
}

function updateWidgetById(widgets: ScreenWidget[], id: string, fn: (w: ScreenWidget) => ScreenWidget): ScreenWidget[] {
    return widgets.map(w => {
        if (w.id === id) return fn(w);
        if (w.children) return { ...w, children: updateWidgetById(w.children, id, fn) };
        return w;
    });
}

function deleteWidgetById(widgets: ScreenWidget[], id: string): ScreenWidget[] {
    return widgets.filter(w => w.id !== id).map(w => w.children ? { ...w, children: deleteWidgetById(w.children, id) } : w);
}

function moveInList(list: ScreenWidget[], id: string, dir: 'up' | 'down'): ScreenWidget[] {
    const idx = list.findIndex(w => w.id === id);
    if (idx !== -1) {
        const next = dir === 'up' ? idx - 1 : idx + 1;
        if (next < 0 || next >= list.length) return list;
        const r = [...list]; [r[idx], r[next]] = [r[next], r[idx]]; return r;
    }
    return list.map(w => w.children ? { ...w, children: moveInList(w.children, id, dir) } : w);
}

function findAndRemove(widgets: ScreenWidget[], id: string): [ScreenWidget[], ScreenWidget | null] {
    let removed: ScreenWidget | null = null;
    const filtered = widgets.filter(w => { if (w.id === id) { removed = w; return false; } return true; });
    const result = filtered.map(w => {
        if (w.children) { const [nc, r] = findAndRemove(w.children, id); if (r) removed = r; return { ...w, children: nc }; }
        return w;
    });
    return [result, removed];
}

function insertAt(widgets: ScreenWidget[], widget: ScreenWidget, targetId: string, position: DropPosition): ScreenWidget[] {
    if (position === 'inside') {
        return widgets.map(w => {
            if (w.id === targetId && w.children !== undefined) return { ...w, children: [...w.children, widget] };
            if (w.children) return { ...w, children: insertAt(w.children, widget, targetId, position) };
            return w;
        });
    }
    const idx = widgets.findIndex(w => w.id === targetId);
    if (idx !== -1) {
        const at = position === 'before' ? idx : idx + 1;
        const r = [...widgets]; r.splice(at, 0, widget); return r;
    }
    return widgets.map(w => { if (w.children) return { ...w, children: insertAt(w.children, widget, targetId, position) }; return w; });
}

function isDescendant(widgets: ScreenWidget[], ancestorId: string, potentialDescId: string): boolean {
    const a = findWidget(widgets, ancestorId);
    if (!a?.children) return false;
    return findWidget(a.children, potentialDescId) !== null;
}

function moveWidget(widgets: ScreenWidget[], dragId: string, target: DropTarget): ScreenWidget[] {
    const [without, dragged] = findAndRemove(widgets, dragId);
    if (!dragged) return widgets;
    if (target.id === '__root__') return [...without, dragged];
    return insertAt(without, dragged, target.id, target.position);
}

function flatWidgetIds(widgets: ScreenWidget[]): string[] {
    return widgets.flatMap(w => [w.id, ...(w.children ? flatWidgetIds(w.children) : [])]);
}

function isTopLevel(widgets: ScreenWidget[], id: string): boolean {
    return widgets.some(w => w.id === id);
}

function deepCloneWithNewIds(widget: ScreenWidget): ScreenWidget {
    const clone: ScreenWidget = { ...widget, id: createId('widget') };
    if (clone.children) clone.children = clone.children.map(deepCloneWithNewIds);
    return clone;
}

// ─── LayerNode ────────────────────────────────────────────────────────────────
const LayerNode: React.FC<{
    widget: ScreenWidget;
    depth: number;
    selectedId: string | null;
    onSelect: (id: string) => void;
    onMoveUp: (id: string) => void;
    onMoveDown: (id: string) => void;
    onDelete: (id: string) => void;
    isFirst: boolean;
    isLast: boolean;
    drag: TreeDragState;
    dragCbs: TreeDragCallbacks;
    collapseGen: number;
    expandGen: number;
}> = ({ widget, depth, selectedId, onSelect, onMoveUp, onMoveDown, onDelete, isFirst, isLast, drag, dragCbs, collapseGen, expandGen }) => {
    const [open, setOpen] = useState(true);
    useEffect(() => { setOpen(false); }, [collapseGen]);
    useEffect(() => { setOpen(true); }, [expandGen]);

    const container = isContainer(widget);
    const label = widget.text || widget.imagePath;
    const isSelected = selectedId === widget.id;
    const isDragging = drag.draggingId === widget.id;
    const dt = drag.dropTarget;
    const isDropBefore = dt?.id === widget.id && dt.position === 'before';
    const isDropAfter  = dt?.id === widget.id && dt.position === 'after';
    const isDropInside = dt?.id === widget.id && dt.position === 'inside';

    const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
        // Ignore palette drags in the tree — only handle tree-reorder drags.
        if (!e.dataTransfer.types.includes('text/plain')) return;
        e.preventDefault(); e.stopPropagation();
        const rect = e.currentTarget.getBoundingClientRect();
        const ratio = (e.clientY - rect.top) / rect.height;
        const position: DropPosition = container
            ? (ratio < 0.3 ? 'before' : ratio > 0.7 ? 'after' : 'inside')
            : (ratio < 0.5 ? 'before' : 'after');
        dragCbs.onDragOver(widget.id, position);
    };

    return (
        <div>
            {isDropBefore && <div className="h-0.5 bg-accent mx-2 rounded-full" />}
            <div
                draggable
                onDragStart={e => { e.dataTransfer.setData('text/plain', widget.id); e.dataTransfer.effectAllowed = 'move'; dragCbs.onDragStart(widget.id); }}
                onDragOver={handleDragOver}
                onDrop={e => { e.preventDefault(); e.stopPropagation(); dragCbs.onDrop(); }}
                onDragEnd={dragCbs.onDragEnd}
                onClick={() => onSelect(widget.id)}
                style={{ paddingLeft: `${depth * 14 + 6}px` }}
                className={`
                    group flex items-center gap-1.5 py-1 pr-1 rounded cursor-pointer select-none transition-all
                    ${isDragging ? 'opacity-30' : ''}
                    ${isDropInside ? 'ring-1 ring-accent ring-inset bg-accent/5' : ''}
                    ${isSelected ? 'bg-accent/15 dark:bg-accent/20' : 'hover:bg-tertiary-hover'}
                `}
            >
                {container ? (
                    <button className="w-3.5 h-3.5 flex-shrink-0 flex items-center justify-center"
                        onClick={e => { e.stopPropagation(); setOpen(o => !o); }}>
                        <svg viewBox="0 0 12 12" className={`w-2.5 h-2.5 transition-transform ${open ? 'rotate-90' : ''} text-secondary`} fill="currentColor">
                            <path d="M4 2l4 4-4 4V2z"/>
                        </svg>
                    </button>
                ) : (
                    <span className="w-3.5 flex-shrink-0" />
                )}
                <span className={`flex-shrink-0 ${WIDGET_ICON_COLORS[widget.type]}`}>
                    {React.cloneElement(WIDGET_ICONS[widget.type] as React.ReactElement, { className: 'w-3.5 h-3.5' })}
                </span>
                <span className="flex-grow min-w-0 flex items-center gap-1 overflow-hidden">
                    <span className={`text-[11px] font-semibold flex-shrink-0 ${isSelected ? 'text-accent' : 'text-primary'}`}>
                        {widget.type}
                    </span>
                    {label && <span className="text-[10px] text-secondary truncate">"{label}"</span>}
                    {container && widget.children !== undefined && (
                        <span className="flex-shrink-0 text-[9px] bg-tertiary text-secondary rounded-full px-1 leading-4 font-mono">{widget.children.length}</span>
                    )}
                </span>
                <span className="flex-shrink-0 text-secondary opacity-20 cursor-grab text-[10px] px-0.5">⠿</span>
                <div className="flex-shrink-0 flex items-center gap-0.5 opacity-0 group-hover:opacity-100" onClick={e => e.stopPropagation()}>
                    <button disabled={isFirst} onClick={() => onMoveUp(widget.id)}
                        className="p-0.5 rounded hover:bg-black/10 dark:hover:bg-white/10 disabled:opacity-20 text-secondary hover:text-primary">
                        <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 8l4-4 4 4"/></svg>
                    </button>
                    <button disabled={isLast} onClick={() => onMoveDown(widget.id)}
                        className="p-0.5 rounded hover:bg-black/10 dark:hover:bg-white/10 disabled:opacity-20 text-secondary hover:text-primary">
                        <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 4l4 4 4-4"/></svg>
                    </button>
                    <button onClick={() => onDelete(widget.id)}
                        className="p-0.5 rounded hover:bg-red-100 dark:hover:bg-red-900/30 text-secondary hover:text-red-500">
                        <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 2l8 8M10 2l-8 8"/></svg>
                    </button>
                </div>
            </div>
            {isDropAfter && <div className="h-0.5 bg-accent mx-2 rounded-full" />}
            {container && open && widget.children && (
                <div className="relative">
                    <div className="absolute top-0 bottom-0 w-px bg-gray-200 dark:bg-gray-700"
                        style={{ left: `${depth * 14 + 12}px` }} />
                    {widget.children.map((child, idx) => (
                        <LayerNode key={child.id} widget={child} depth={depth + 1}
                            selectedId={selectedId} onSelect={onSelect}
                            onMoveUp={onMoveUp} onMoveDown={onMoveDown} onDelete={onDelete}
                            isFirst={idx === 0} isLast={idx === widget.children!.length - 1}
                            drag={drag} dragCbs={dragCbs}
                            collapseGen={collapseGen} expandGen={expandGen} />
                    ))}
                    {widget.children.length === 0 && (
                        <p className="text-[9px] text-secondary italic py-1"
                            style={{ paddingLeft: `${(depth + 1) * 14 + 22}px` }}>empty</p>
                    )}
                </div>
            )}
        </div>
    );
};

// ─── CanvasWidget ─────────────────────────────────────────────────────────────
// Renders one widget node on the WYSIWYG canvas.
// Top-level widgets are absolutely positioned (game pixels → % of canvas).
// Container children are flow-positioned inside their parent flex layout.
const CanvasWidget: React.FC<{ widget: ScreenWidget; isTopLevel: boolean }> = ({ widget, isTopLevel }) => {
    const ctx = React.useContext(CanvasCtx);
    const { selectedId, inlineEditId, inlineEditText, containerDropTarget, gameWidth, gameHeight } = ctx;
    const isSelected = selectedId === widget.id;
    const editing = inlineEditId === widget.id;
    const container = isContainer(widget);
    const isContainerDrop = containerDropTarget === widget.id;

    // Top-level: game-pixel position → CSS percentage of canvas dimensions.
    const posStyle: React.CSSProperties = {};
    if (isTopLevel) {
        const { x, y } = getWidgetDisplayPos(widget, gameWidth, gameHeight);
        posStyle.position = 'absolute';
        posStyle.left  = `${(x / gameWidth)  * 100}%`;
        posStyle.top   = `${(y / gameHeight) * 100}%`;
        if (widget.xsize !== undefined) posStyle.width  = `${(widget.xsize / gameWidth)  * 100}%`;
        if (widget.ysize !== undefined) posStyle.height = `${(widget.ysize / gameHeight) * 100}%`;
    }

    const InlineInput: React.FC<{ className?: string }> = ({ className = '' }) => (
        <input autoFocus
            className={`bg-transparent outline-none border-b border-accent w-full ${className}`}
            value={inlineEditText}
            onChange={e => ctx.onInlineEditChange(e.target.value)}
            onBlur={ctx.onInlineEditCommit}
            onKeyDown={e => { if (e.key === 'Enter' || e.key === 'Escape') { e.preventDefault(); ctx.onInlineEditCommit(); } }}
            onClick={e => e.stopPropagation()}
        />
    );

    const renderContent = () => {
        switch (widget.type) {
            case 'null':
                return (
                    <div className="border border-dashed border-gray-600 rounded flex items-center justify-center px-3"
                        style={{ minWidth: 40, minHeight: 16 }}>
                        <span className="text-[9px] text-gray-500 italic">spacer</span>
                    </div>
                );

            case 'text':
                return (
                    <div className="px-2 py-1 rounded" style={{ minWidth: 40 }}>
                        {editing
                            ? <InlineInput className="text-white text-sm font-medium" />
                            : <span className="text-sm text-white font-medium whitespace-nowrap select-none"
                                onDoubleClick={e => { e.stopPropagation(); ctx.onInlineEditStart(widget); }}>
                                {widget.text || 'Text'}
                              </span>
                        }
                    </div>
                );

            case 'textbutton':
                return (
                    <div className="px-4 py-1.5 rounded-full border-2 border-yellow-400/70 bg-yellow-900/30 text-center"
                        style={{ minWidth: 80 }}>
                        {editing
                            ? <InlineInput className="text-yellow-200 text-sm font-semibold text-center" />
                            : <span className="text-sm font-semibold text-yellow-200 whitespace-nowrap select-none"
                                onDoubleClick={e => { e.stopPropagation(); ctx.onInlineEditStart(widget); }}>
                                {widget.text || 'Button'}
                              </span>
                        }
                    </div>
                );

            case 'button':
                return (
                    <div className="rounded border-2 border-orange-500/60 bg-orange-900/20 p-1.5"
                        style={{ minWidth: 60, minHeight: 32 }}>
                        {widget.children && widget.children.length > 0
                            ? <div className="flex flex-col gap-1">
                                {widget.children.map(c => <CanvasWidget key={c.id} widget={c} isTopLevel={false} />)}
                              </div>
                            : <span className="text-[10px] text-orange-300/60 italic block text-center">button</span>
                        }
                    </div>
                );

            case 'image': {
                const imgDrop = {
                    onDrop: (e: React.DragEvent) => {
                        e.preventDefault(); e.stopPropagation();
                        const path = e.dataTransfer.getData('application/renpy-image-path');
                        if (!path) return;
                        const dataUrl = e.dataTransfer.getData('application/renpy-image-dataurl');
                        ctx.onUpdateWidget(widget.id, w => ({ ...w, imagePath: path, ...(dataUrl ? { imageDataUrl: dataUrl } : {}) }));
                    },
                    onDragOver: (e: React.DragEvent) => e.preventDefault(),
                };
                return (
                    <div className="border border-green-500/50 bg-green-900/20 flex items-center justify-center overflow-hidden rounded"
                        style={{ minWidth: 80, minHeight: 60 }} {...imgDrop}>
                        {widget.imageDataUrl
                            ? <img src={widget.imageDataUrl} alt={widget.imagePath} className="w-full h-full object-contain" />
                            : <div className="flex flex-col items-center gap-1 p-2">
                                <svg viewBox="0 0 20 20" className="w-5 h-5 text-green-400/60" fill="none">
                                    <rect x="2" y="4" width="16" height="12" rx="2" stroke="currentColor" strokeWidth="1.5"/>
                                    <circle cx="7" cy="8.5" r="1.5" fill="currentColor" opacity="0.7"/>
                                    <path d="M2 13.5l4.5-4 3 3 2.5-2.5 6 4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.8"/>
                                </svg>
                                <span className="text-[9px] text-green-400/70 text-center max-w-[80px] truncate">
                                    {widget.imagePath || 'drop image'}
                                </span>
                              </div>
                        }
                    </div>
                );
            }

            case 'imagebutton': {
                const ibDrop = {
                    onDrop: (e: React.DragEvent) => {
                        e.preventDefault(); e.stopPropagation();
                        const path = e.dataTransfer.getData('application/renpy-image-path');
                        if (!path) return;
                        const dataUrl = e.dataTransfer.getData('application/renpy-image-dataurl');
                        ctx.onUpdateWidget(widget.id, w => ({ ...w, imagePath: path, ...(dataUrl ? { imageDataUrl: dataUrl } : {}) }));
                    },
                    onDragOver: (e: React.DragEvent) => e.preventDefault(),
                };
                return (
                    <div className="border-2 border-lime-500/50 bg-lime-900/20 flex flex-col items-center justify-center overflow-hidden rounded"
                        style={{ minWidth: 60, minHeight: 40 }} {...ibDrop}>
                        {widget.imageDataUrl
                            ? <img src={widget.imageDataUrl} alt={widget.imagePath} className="w-full h-full object-contain" />
                            : <>
                                <svg viewBox="0 0 20 20" className="w-5 h-5 text-lime-400/60" fill="none">
                                    <rect x="2" y="3" width="16" height="10" rx="2" stroke="currentColor" strokeWidth="1.5"/>
                                    <circle cx="6.5" cy="7" r="1.2" fill="currentColor" opacity="0.6"/>
                                    <path d="M2 11l3.5-3 2.5 2 2-2 6 4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.7"/>
                                </svg>
                                <span className="text-[9px] text-lime-400/70">{widget.imagePath || 'img btn'}</span>
                              </>
                        }
                    </div>
                );
            }

            case 'bar':
                return (
                    <div style={{ minWidth: 120, minHeight: 20 }} className="py-1 px-1">
                        <div className="w-full h-2.5 rounded-full bg-gray-700 overflow-hidden border border-teal-500/40">
                            <div className="h-full w-3/5 rounded-full bg-teal-500/60" />
                        </div>
                    </div>
                );

            case 'input':
                return (
                    <div className="border-2 border-pink-500/50 bg-gray-800/60 rounded flex items-center gap-1 px-2 py-1.5"
                        style={{ minWidth: 100, minHeight: 30 }}>
                        <span className="flex-grow text-xs text-gray-500 italic">input…</span>
                        <span className="w-px h-3.5 bg-pink-400 opacity-70" />
                    </div>
                );

            case 'vbox':
            case 'hbox':
            case 'frame': {
                const isHbox = widget.type === 'hbox';
                const borderCls = widget.type === 'vbox'  ? 'border-blue-500/40'   :
                                  widget.type === 'hbox'  ? 'border-indigo-500/40' :
                                                            'border-purple-500/40';
                const bgCls    = widget.type === 'vbox'  ? 'bg-blue-900/15'        :
                                  widget.type === 'hbox'  ? 'bg-indigo-900/15'     :
                                                            'bg-purple-900/15';
                const empty = !widget.children || widget.children.length === 0;
                return (
                    <div className={`border ${borderCls} ${bgCls} rounded p-1.5 ${isContainerDrop ? 'ring-2 ring-accent ring-inset' : ''}`}
                        style={{ minWidth: 60, minHeight: 36 }}
                        onDragOver={e => ctx.onContainerDragOver(e, widget.id)}
                        onDragLeave={ctx.onContainerDragLeave}
                        onDrop={e => ctx.onContainerDrop(e, widget.id)}
                    >
                        {empty
                            ? <span className="text-[9px] text-gray-500/70 italic block text-center py-0.5">{widget.type} — drop here</span>
                            : <div className={`flex gap-1 ${isHbox ? 'flex-row flex-wrap' : 'flex-col'}`}>
                                {widget.children!.map(c => <CanvasWidget key={c.id} widget={c} isTopLevel={false} />)}
                              </div>
                        }
                    </div>
                );
            }

            default: return null;
        }
    };

    const CURSOR_MAP: Record<ResizeHandleDir, string> = {
        nw: 'nw-resize', ne: 'ne-resize', sw: 'sw-resize', se: 'se-resize',
    };

    return (
        <div
            style={posStyle}
            className={`group/cw relative select-none
                ${isTopLevel ? 'cursor-move' : 'cursor-pointer'}
                ${isTopLevel && widget.xsize === undefined ? 'inline-block' : ''}
            `}
            onClick={e => { e.stopPropagation(); ctx.onSelect(widget.id); }}
            onPointerDown={isTopLevel ? e => ctx.onWidgetPointerDown(e, widget.id) : undefined}
        >
            {renderContent()}

            {/* Selection ring */}
            {isSelected && (
                <div className="absolute inset-0 rounded pointer-events-none ring-2 ring-accent" />
            )}

            {/* Type + coords label above selected widget */}
            {isSelected && (
                <div className="absolute -top-5 left-0 flex items-center gap-1 bg-accent text-white
                    text-[9px] font-bold px-1.5 py-0.5 rounded-t whitespace-nowrap pointer-events-none z-20">
                    {React.cloneElement(WIDGET_ICONS[widget.type] as React.ReactElement, { className: 'w-2.5 h-2.5' })}
                    {widget.type}
                    {(widget.xpos !== undefined || widget.xalign !== undefined) && (
                        <span className="font-mono opacity-75 ml-0.5">
                            {widget.xpos !== undefined
                                ? `${widget.xpos},${widget.ypos ?? 0}`
                                : `${Math.round((widget.xalign ?? 0) * 100)}%,${Math.round((widget.yalign ?? 0) * 100)}%`}
                        </span>
                    )}
                </div>
            )}

            {/* Corner resize handles — only for selected top-level widgets */}
            {isSelected && isTopLevel && (['nw', 'ne', 'sw', 'se'] as ResizeHandleDir[]).map(handle => (
                <div key={handle}
                    className="absolute w-2.5 h-2.5 bg-white border-2 border-accent rounded-sm z-20 shadow"
                    style={{
                        cursor: CURSOR_MAP[handle],
                        top:    handle.startsWith('n') ? -5 : 'auto',
                        bottom: handle.startsWith('s') ? -5 : 'auto',
                        left:   handle.endsWith('w')   ? -5 : 'auto',
                        right:  handle.endsWith('e')   ? -5 : 'auto',
                    }}
                    onPointerDown={e => { e.stopPropagation(); ctx.onResizePointerDown(e, widget.id, handle); }}
                />
            ))}
        </div>
    );
};

// ─── PropertiesPanel ──────────────────────────────────────────────────────────
const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => (
    <div>
        <label className="block text-[10px] font-semibold text-secondary uppercase tracking-wide mb-1">{label}</label>
        {children}
    </div>
);

const PropertiesPanel: React.FC<{
    widget: ScreenWidget | null;
    composition: ScreenLayoutComposition;
    onUpdateWidget: (id: string, fn: (w: ScreenWidget) => ScreenWidget) => void;
    onUpdateComposition: (fn: (c: ScreenLayoutComposition) => ScreenLayoutComposition) => void;
    screenName: string;
    onRenameScreen: (name: string) => void;
}> = ({ widget, composition, onUpdateWidget, onUpdateComposition, screenName, onRenameScreen }) => {
    const [localName, setLocalName] = useState(screenName);
    useEffect(() => { setLocalName(screenName); }, [screenName]);

    const str = (v: string | undefined) => v ?? '';
    const num = (v: number | undefined) => v !== undefined ? String(v) : '';

    const set = (field: keyof ScreenWidget, value: string | number | undefined) => {
        if (!widget) return;
        onUpdateWidget(widget.id, w => ({ ...w, [field]: value }));
    };
    const setNum = (field: keyof ScreenWidget, raw: string) => {
        const n = parseFloat(raw);
        set(field, isNaN(n) ? undefined : n);
    };

    const inputCls = 'w-full px-2 py-1.5 rounded-md bg-primary border border-primary text-sm focus:outline-none focus:ring-1 focus:ring-accent transition-colors';

    if (!widget) {
        return (
            <div className="p-3 space-y-4">
                <div className="flex items-center gap-2 pb-1 border-b border-primary">
                    <svg viewBox="0 0 20 20" className="w-4 h-4 text-secondary" fill="none">
                        <rect x="3" y="3" width="14" height="14" rx="3" stroke="currentColor" strokeWidth="1.5"/>
                        <path d="M7 10h6M10 7v6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                    </svg>
                    <span className="text-xs font-bold text-primary">Screen Properties</span>
                </div>
                <Field label="Screen Name">
                    <input className={inputCls} value={localName}
                        onChange={e => setLocalName(e.target.value)}
                        onBlur={() => { if (localName !== screenName) onRenameScreen(localName); }} />
                </Field>
                <div className="grid grid-cols-2 gap-2">
                    <Field label="Width">
                        <input type="number" className={inputCls} value={composition.gameWidth}
                            onChange={e => onUpdateComposition(c => ({ ...c, gameWidth: parseInt(e.target.value) || 1920 }))} />
                    </Field>
                    <Field label="Height">
                        <input type="number" className={inputCls} value={composition.gameHeight}
                            onChange={e => onUpdateComposition(c => ({ ...c, gameHeight: parseInt(e.target.value) || 1080 }))} />
                    </Field>
                </div>
                <div className="grid grid-cols-2 gap-2">
                    <Field label="Z-Order">
                        <input type="number" className={inputCls} value={composition.zorder}
                            onChange={e => onUpdateComposition(c => ({ ...c, zorder: parseInt(e.target.value) || 0 }))} />
                    </Field>
                    <div className="flex items-center gap-2 pt-5">
                        <input type="checkbox" id="modal-check" checked={composition.modal}
                            className="w-4 h-4 rounded accent-accent cursor-pointer"
                            onChange={e => onUpdateComposition(c => ({ ...c, modal: e.target.checked }))} />
                        <label htmlFor="modal-check" className="text-xs font-semibold text-secondary cursor-pointer">Modal</label>
                    </div>
                </div>
            </div>
        );
    }

    const container = isContainer(widget);
    const hasText   = ['text', 'textbutton'].includes(widget.type);
    const hasAction = ['textbutton', 'button', 'imagebutton'].includes(widget.type);
    const hasImage  = ['image', 'imagebutton'].includes(widget.type);

    return (
        <div className="p-3 space-y-4">
            <div className="flex items-center gap-2 pb-1 border-b border-primary">
                <span className={WIDGET_ICON_COLORS[widget.type]}>{WIDGET_ICONS[widget.type]}</span>
                <span className="text-xs font-bold text-primary">{WIDGET_LABELS[widget.type]}</span>
            </div>

            {hasText && (
                <Field label="Text">
                    <input className={inputCls} value={str(widget.text)} onChange={e => set('text', e.target.value)} />
                </Field>
            )}
            {hasAction && (
                <Field label="Action">
                    <input className={`${inputCls} font-mono text-xs`} value={str(widget.action)}
                        onChange={e => set('action', e.target.value)} placeholder="Return()" />
                </Field>
            )}
            {hasImage && (
                <Field label="Image Path — or drag from Assets">
                    <input className={`${inputCls} font-mono text-xs`} value={str(widget.imagePath)}
                        onChange={e => set('imagePath', e.target.value)} placeholder="gui/button.png"
                        onDrop={e => {
                            e.preventDefault();
                            const path = e.dataTransfer.getData('application/renpy-image-path');
                            if (!path) return;
                            const dataUrl = e.dataTransfer.getData('application/renpy-image-dataurl');
                            onUpdateWidget(widget.id, w => ({ ...w, imagePath: path, ...(dataUrl ? { imageDataUrl: dataUrl } : {}) }));
                        }}
                        onDragOver={e => e.preventDefault()}
                    />
                </Field>
            )}

            <Field label="Style">
                <input className={`${inputCls} font-mono text-xs`} value={str(widget.style)}
                    onChange={e => set('style', e.target.value || undefined)} placeholder="default" />
            </Field>

            {/* Position */}
            <div>
                <div className="flex items-center gap-1.5 mb-2">
                    <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none">
                        <path d="M8 2v12M2 8h12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                        <circle cx="8" cy="8" r="2.5" stroke="currentColor" strokeWidth="1.2"/>
                    </svg>
                    <span className="text-[10px] font-semibold text-secondary uppercase tracking-wide">Position</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                    <Field label="xpos (px)">
                        <input type="number" className={inputCls} value={num(widget.xpos)}
                            onChange={e => setNum('xpos', e.target.value)} placeholder="—" />
                    </Field>
                    <Field label="ypos (px)">
                        <input type="number" className={inputCls} value={num(widget.ypos)}
                            onChange={e => setNum('ypos', e.target.value)} placeholder="—" />
                    </Field>
                    <Field label="xalign (0–1)">
                        <input type="number" step="0.05" min="0" max="1" className={inputCls}
                            value={num(widget.xalign)} onChange={e => setNum('xalign', e.target.value)} placeholder="—" />
                    </Field>
                    <Field label="yalign (0–1)">
                        <input type="number" step="0.05" min="0" max="1" className={inputCls}
                            value={num(widget.yalign)} onChange={e => setNum('yalign', e.target.value)} placeholder="—" />
                    </Field>
                </div>
                <p className="text-[10px] text-secondary mt-1.5 leading-snug opacity-60">
                    Drag widget on canvas to set xpos/ypos. xalign/yalign = 0–1 fraction of screen.
                </p>
            </div>

            {/* Size */}
            <div>
                <div className="flex items-center gap-1.5 mb-2">
                    <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none">
                        <rect x="2" y="2" width="12" height="12" rx="1.5" stroke="currentColor" strokeWidth="1.5"/>
                        <path d="M10 2v4M14 6h-4M6 10v4M2 10h4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" opacity="0.6"/>
                    </svg>
                    <span className="text-[10px] font-semibold text-secondary uppercase tracking-wide">Size</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                    <Field label="xsize (px)">
                        <input type="number" className={inputCls} value={num(widget.xsize)}
                            onChange={e => setNum('xsize', e.target.value)} placeholder="auto" />
                    </Field>
                    <Field label="ysize (px)">
                        <input type="number" className={inputCls} value={num(widget.ysize)}
                            onChange={e => setNum('ysize', e.target.value)} placeholder="auto" />
                    </Field>
                </div>
                <p className="text-[10px] text-secondary mt-1.5 leading-snug opacity-60">
                    Drag corner handles on canvas to resize.
                </p>
            </div>

            {container && (
                <p className="text-[10px] text-secondary italic leading-snug bg-tertiary rounded px-2 py-1.5">
                    Container children are flow-positioned by their parent. Add children via the Layers panel or by dropping onto this widget on the canvas.
                </p>
            )}
        </div>
    );
};

// ─── Main Component ───────────────────────────────────────────────────────────
const ScreenLayoutComposer: React.FC<ScreenLayoutComposerProps> = ({
    composition, onCompositionChange, screenName, onRenameScreen,
    isLocked = false, isActive = true, onDuplicate, onGoToCode, activeEditor,
}) => {
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [codeOpen, setCodeOpen] = useState(false);
    const [legendOpen, setLegendOpen] = useState(false);
    const [clipboardWidget, setClipboardWidget] = useState<ScreenWidget | null>(null);
    const [inlineEditId, setInlineEditId] = useState<string | null>(null);
    const [inlineEditText, setInlineEditText] = useState('');
    const [containerDropTarget, setContainerDropTarget] = useState<string | null>(null);
    const [canvasDropActive, setCanvasDropActive] = useState(false);

    // Layer tree state
    const [dragState, setDragState] = useState<TreeDragState>({ draggingId: null, dropTarget: null });
    const [collapseGen, setCollapseGen] = useState(0);
    const [expandGen, setExpandGen]     = useState(0);

    // Canvas interaction refs — global pointer listeners read these directly to avoid stale closures.
    const canvasRef      = useRef<HTMLDivElement>(null);
    const canvasDragRef  = useRef<CanvasDragState | null>(null);
    const resizeDragRef  = useRef<ResizeDragState | null>(null);

    const selectedWidget = selectedId ? findWidget(composition.widgets, selectedId) ?? null : null;

    // ── Mutation helpers ──────────────────────────────────────────────────────
    const handleUpdateWidget = useCallback((id: string, fn: (w: ScreenWidget) => ScreenWidget) => {
        onCompositionChange(c => ({ ...c, widgets: updateWidgetById(c.widgets, id, fn) }));
    }, [onCompositionChange]);

    const handleDeleteWidget = useCallback((id: string) => {
        if (selectedId === id) setSelectedId(null);
        onCompositionChange(c => ({ ...c, widgets: deleteWidgetById(c.widgets, id) }));
    }, [onCompositionChange, selectedId]);

    const handleMoveWidget = useCallback((id: string, dir: 'up' | 'down') => {
        onCompositionChange(c => ({ ...c, widgets: moveInList(c.widgets, id, dir) }));
    }, [onCompositionChange]);

    // Click-to-add from palette (fallback when not dragging).
    const handleAddWidget = useCallback((type: ScreenWidgetType) => {
        const widget = makeWidget(type);
        if (selectedId) {
            const sel = findWidget(composition.widgets, selectedId);
            if (sel && isContainer(sel)) {
                onCompositionChange(c => ({ ...c, widgets: addToContainer(c.widgets, selectedId, widget) }));
                setSelectedId(widget.id);
                return;
            }
        }
        // Cascade-place on canvas so subsequent adds don't all pile on (0, 0).
        const count = flatWidgetIds(composition.widgets).length % 10;
        onCompositionChange(c => ({
            ...c,
            widgets: [...c.widgets, { ...widget, xpos: 20 + count * 20, ypos: 20 + count * 20 }],
        }));
        setSelectedId(widget.id);
    }, [selectedId, composition.widgets, onCompositionChange]);

    // ── Inline edit ───────────────────────────────────────────────────────────
    const handleInlineEditStart = useCallback((w: ScreenWidget) => {
        setInlineEditId(w.id);
        setInlineEditText(w.text ?? '');
    }, []);

    const handleInlineEditCommit = useCallback(() => {
        if (!inlineEditId) return;
        handleUpdateWidget(inlineEditId, w => ({ ...w, text: inlineEditText }));
        setInlineEditId(null);
    }, [inlineEditId, inlineEditText, handleUpdateWidget]);

    // ── Canvas widget drag ────────────────────────────────────────────────────
    const handleWidgetPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>, id: string) => {
        if (isLocked) return;
        e.stopPropagation();
        setSelectedId(id);
        if (!isTopLevel(composition.widgets, id)) return;
        const canvas = canvasRef.current;
        if (!canvas) return;
        const widget = findWidget(composition.widgets, id);
        if (!widget) return;
        const { x: wx, y: wy } = getWidgetDisplayPos(widget, composition.gameWidth, composition.gameHeight);
        const g = clientToGame(e.clientX, e.clientY, canvas, composition.gameWidth, composition.gameHeight);
        canvasDragRef.current = { widgetId: id, offsetX: g.x - wx, offsetY: g.y - wy };
    }, [isLocked, composition]);

    // ── Resize handle drag ────────────────────────────────────────────────────
    const handleResizePointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>, id: string, handle: ResizeHandleDir) => {
        if (isLocked) return;
        e.stopPropagation();
        const canvas = canvasRef.current;
        if (!canvas) return;
        const widget = findWidget(composition.widgets, id);
        if (!widget) return;
        const { x, y } = getWidgetDisplayPos(widget, composition.gameWidth, composition.gameHeight);
        const g = clientToGame(e.clientX, e.clientY, canvas, composition.gameWidth, composition.gameHeight);
        // Measure the rendered element's current size in game pixels.
        const canvasRect = canvas.getBoundingClientRect();
        const el = canvas.querySelector(`[data-wid="${id}"]`) as HTMLElement | null;
        const startW = widget.xsize ?? (el ? Math.round((el.offsetWidth  / canvasRect.width)  * composition.gameWidth)  : 200);
        const startH = widget.ysize ?? (el ? Math.round((el.offsetHeight / canvasRect.height) * composition.gameHeight) : 100);
        resizeDragRef.current = { widgetId: id, handle, startPointerX: g.x, startPointerY: g.y, startX: x, startY: y, startW, startH };
    }, [isLocked, composition]);

    // Global pointer events for drag + resize (follows the app's canvas pattern).
    useEffect(() => {
        const onMove = (e: PointerEvent) => {
            const canvas = canvasRef.current;
            if (!canvas) return;
            const { gameWidth, gameHeight } = composition;

            if (canvasDragRef.current) {
                const { widgetId, offsetX, offsetY } = canvasDragRef.current;
                const g = clientToGame(e.clientX, e.clientY, canvas, gameWidth, gameHeight);
                const nx = Math.max(0, Math.min(gameWidth  - 1, g.x - offsetX));
                const ny = Math.max(0, Math.min(gameHeight - 1, g.y - offsetY));
                handleUpdateWidget(widgetId, w => ({ ...w, xpos: nx, ypos: ny, xalign: undefined, yalign: undefined }));
            }

            if (resizeDragRef.current) {
                const { widgetId, handle, startPointerX, startPointerY, startX, startY, startW, startH } = resizeDragRef.current;
                const g  = clientToGame(e.clientX, e.clientY, canvas, gameWidth, gameHeight);
                const dx = g.x - startPointerX;
                const dy = g.y - startPointerY;
                let nx = startX, ny = startY, nw = startW, nh = startH;

                if      (handle === 'se') { nw = Math.max(20, startW + dx);       nh = Math.max(20, startH + dy); }
                else if (handle === 'sw') { nx = startX + dx; nw = Math.max(20, startW - dx); nh = Math.max(20, startH + dy); }
                else if (handle === 'ne') { ny = startY + dy; nw = Math.max(20, startW + dx); nh = Math.max(20, startH - dy); }
                else if (handle === 'nw') { nx = startX + dx; ny = startY + dy; nw = Math.max(20, startW - dx); nh = Math.max(20, startH - dy); }

                handleUpdateWidget(widgetId, w => ({
                    ...w,
                    xpos: Math.round(nx), ypos: Math.round(ny),
                    xsize: Math.round(nw), ysize: Math.round(nh),
                    xalign: undefined, yalign: undefined,
                }));
            }
        };

        const onUp = () => { canvasDragRef.current = null; resizeDragRef.current = null; };

        window.addEventListener('pointermove', onMove);
        window.addEventListener('pointerup', onUp);
        return () => { window.removeEventListener('pointermove', onMove); window.removeEventListener('pointerup', onUp); };
    }, [composition, handleUpdateWidget]);

    // ── Palette → canvas drop ─────────────────────────────────────────────────
    const handleCanvasDragOver = useCallback((e: React.DragEvent<HTMLDivElement>) => {
        if (!e.dataTransfer.types.includes('widget-type')) return;
        e.preventDefault();
        e.dataTransfer.dropEffect = 'copy';
        setCanvasDropActive(true);
    }, []);

    const handleCanvasDragLeave = useCallback((e: React.DragEvent<HTMLDivElement>) => {
        if (!e.currentTarget.contains(e.relatedTarget as Node)) setCanvasDropActive(false);
    }, []);

    const handleCanvasDrop = useCallback((e: React.DragEvent<HTMLDivElement>) => {
        e.preventDefault();
        setCanvasDropActive(false);
        const type = e.dataTransfer.getData('widget-type') as ScreenWidgetType;
        if (!type || !canvasRef.current) return;
        const g = clientToGame(e.clientX, e.clientY, canvasRef.current, composition.gameWidth, composition.gameHeight);
        const widget = { ...makeWidget(type), xpos: g.x, ypos: g.y };
        onCompositionChange(c => ({ ...c, widgets: [...c.widgets, widget] }));
        setSelectedId(widget.id);
    }, [composition.gameWidth, composition.gameHeight, onCompositionChange]);

    // ── Palette → container drop ──────────────────────────────────────────────
    const handleContainerDragOver = useCallback((e: React.DragEvent<HTMLDivElement>, id: string) => {
        if (!e.dataTransfer.types.includes('widget-type')) return;
        e.preventDefault(); e.stopPropagation();
        e.dataTransfer.dropEffect = 'copy';
        setContainerDropTarget(id);
        setCanvasDropActive(false);
    }, []);

    const handleContainerDrop = useCallback((e: React.DragEvent<HTMLDivElement>, containerId: string) => {
        e.preventDefault(); e.stopPropagation();
        setContainerDropTarget(null);
        const type = e.dataTransfer.getData('widget-type') as ScreenWidgetType;
        if (!type) return;
        const widget = makeWidget(type);
        onCompositionChange(c => ({ ...c, widgets: addToContainer(c.widgets, containerId, widget) }));
        setSelectedId(widget.id);
    }, [onCompositionChange]);

    const handleContainerDragLeave = useCallback(() => setContainerDropTarget(null), []);

    // ── Keyboard shortcuts ────────────────────────────────────────────────────
    useEffect(() => {
        if (!isActive) return;
        const onKey = (e: KeyboardEvent) => {
            const tag = (e.target as HTMLElement).tagName;
            const inInput = tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT';

            if (e.key === 'Escape') {
                if (inlineEditId) { setInlineEditId(null); return; }
                setSelectedId(null); return;
            }

            if (e.key === 'Tab' && !inInput) {
                e.preventDefault();
                const ids = flatWidgetIds(composition.widgets);
                if (!ids.length) return;
                const idx = selectedId ? ids.indexOf(selectedId) : -1;
                setSelectedId(ids[e.shiftKey ? (idx - 1 + ids.length) % ids.length : (idx + 1) % ids.length]);
                return;
            }

            if ((e.ctrlKey || e.metaKey) && e.key === 'c' && selectedWidget) {
                setClipboardWidget(selectedWidget); return;
            }

            if ((e.ctrlKey || e.metaKey) && e.key === 'v' && clipboardWidget) {
                e.preventDefault();
                const pasted = deepCloneWithNewIds(clipboardWidget);
                onCompositionChange(c => ({
                    ...c,
                    widgets: [...c.widgets, {
                        ...pasted,
                        xpos: (pasted.xpos ?? 0) + 20,
                        ypos: (pasted.ypos ?? 0) + 20,
                    }],
                }));
                setSelectedId(pasted.id);
                return;
            }

            if (inInput) return;

            if ((e.key === 'Delete' || e.key === 'Backspace') && selectedId) {
                e.preventDefault(); handleDeleteWidget(selectedId); return;
            }

            if (selectedId && ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(e.key)) {
                e.preventDefault();
                if (!isTopLevel(composition.widgets, selectedId)) return;
                const amount = e.shiftKey ? 10 : 1;
                const dx = e.key === 'ArrowLeft' ? -amount : e.key === 'ArrowRight' ? amount : 0;
                const dy = e.key === 'ArrowUp'   ? -amount : e.key === 'ArrowDown'  ? amount : 0;
                handleUpdateWidget(selectedId, w => {
                    const { x, y } = getWidgetDisplayPos(w, composition.gameWidth, composition.gameHeight);
                    return { ...w, xpos: x + dx, ypos: y + dy, xalign: undefined, yalign: undefined };
                });
            }
        };
        window.addEventListener('keydown', onKey);
        return () => window.removeEventListener('keydown', onKey);
    }, [isActive, selectedId, selectedWidget, clipboardWidget, inlineEditId,
        handleDeleteWidget, handleUpdateWidget, onCompositionChange,
        composition.widgets, composition.gameWidth, composition.gameHeight]);

    // ── Layer tree drag callbacks ──────────────────────────────────────────────
    const rootDropActive = dragState.dropTarget?.id === '__root__';

    const dragCbs: TreeDragCallbacks = {
        onDragStart: id => setDragState({ draggingId: id, dropTarget: null }),
        onDragOver:  (id, position) => {
            setDragState(prev => {
                if (prev.dropTarget?.id === id && prev.dropTarget.position === position) return prev;
                return { ...prev, dropTarget: { id, position } };
            });
        },
        onDrop: () => {
            const { draggingId, dropTarget } = dragState;
            if (!draggingId || !dropTarget) { setDragState({ draggingId: null, dropTarget: null }); return; }
            if (draggingId === dropTarget.id) { setDragState({ draggingId: null, dropTarget: null }); return; }
            if (dropTarget.position === 'inside' && isDescendant(composition.widgets, draggingId, dropTarget.id)) {
                setDragState({ draggingId: null, dropTarget: null }); return;
            }
            onCompositionChange(c => ({ ...c, widgets: moveWidget(c.widgets, draggingId, dropTarget) }));
            setDragState({ draggingId: null, dropTarget: null });
        },
        onDragEnd: () => setDragState({ draggingId: null, dropTarget: null }),
    };

    // ── Generated code ────────────────────────────────────────────────────────
    const editorIndent = (() => {
        const opts = activeEditor?.getModel()?.getOptions();
        if (!opts) return '    ';
        return opts.insertSpaces ? ' '.repeat(opts.tabSize) : '\t';
    })();
    const generatedCode = generateScreenCode(composition, editorIndent);

    // ── Canvas context object ─────────────────────────────────────────────────
    const canvasCtx: CanvasCtxValue = {
        selectedId, inlineEditId, inlineEditText, containerDropTarget,
        gameWidth: composition.gameWidth, gameHeight: composition.gameHeight,
        onSelect: setSelectedId,
        onWidgetPointerDown:  handleWidgetPointerDown,
        onResizePointerDown:  handleResizePointerDown,
        onInlineEditChange:   setInlineEditText,
        onInlineEditCommit:   handleInlineEditCommit,
        onInlineEditStart:    handleInlineEditStart,
        onUpdateWidget:       handleUpdateWidget,
        onContainerDragOver:  handleContainerDragOver,
        onContainerDrop:      handleContainerDrop,
        onContainerDragLeave: handleContainerDragLeave,
    };

    // ─────────────────────────────────────────────────────────────────────────
    return (
        <div className="h-full flex flex-col bg-primary text-primary overflow-hidden">

            {/* ── Header ── */}
            <div className="flex-none flex items-center gap-3 px-4 py-2.5 border-b border-primary bg-secondary">
                <svg viewBox="0 0 20 20" className="w-5 h-5 text-accent flex-shrink-0" fill="none">
                    <rect x="2" y="2" width="16" height="16" rx="3" stroke="currentColor" strokeWidth="1.5"/>
                    <rect x="5" y="5" width="4" height="10" rx="1" fill="currentColor" opacity="0.4"/>
                    <rect x="11" y="5" width="4" height="4"  rx="1" fill="currentColor" opacity="0.4"/>
                    <rect x="11" y="11" width="4" height="4" rx="1" fill="currentColor" opacity="0.4"/>
                </svg>
                <div>
                    <span className="text-xs text-secondary">Screen Composer</span>
                    <span className="ml-2 font-mono text-sm font-bold text-primary">{screenName}</span>
                </div>
                <div className="flex-grow" />
                <button onClick={() => setLegendOpen(o => !o)} title="Keyboard shortcuts"
                    className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-semibold transition-colors
                        ${legendOpen ? 'bg-accent text-white hover:bg-accent-hover' : 'bg-tertiary text-secondary hover:bg-tertiary-hover hover:text-primary border border-primary'}`}>
                    <svg viewBox="0 0 16 16" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
                        <rect x="1" y="4" width="14" height="8" rx="1.5"/>
                        <path d="M4 7.5h1.5M7.5 7.5h1M10.5 7.5h1M4 10.5h8" strokeWidth="1.3" opacity="0.7"/>
                    </svg>
                    Shortcuts
                </button>
                <button onClick={() => setCodeOpen(o => !o)}
                    className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-colors
                        ${codeOpen ? 'bg-accent text-white hover:bg-accent-hover' : 'bg-tertiary text-secondary hover:bg-tertiary-hover hover:text-primary border border-primary'}`}>
                    <svg viewBox="0 0 16 16" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M5 4L1 8l4 4M11 4l4 4-4 4M9 2l-2 12"/>
                    </svg>
                    {codeOpen ? 'Hide Code' : 'Show Code'}
                </button>
            </div>

            {/* ── Locked banner ── */}
            {isLocked && (
                <div className="flex-none flex items-center gap-3 px-4 py-2.5 bg-amber-50 dark:bg-amber-900/25 border-b border-amber-300 dark:border-amber-700">
                    <svg viewBox="0 0 20 20" className="w-4 h-4 text-amber-600 dark:text-amber-400 flex-shrink-0" fill="none">
                        <path d="M10 2a4 4 0 00-4 4v2H5a2 2 0 00-2 2v7a2 2 0 002 2h10a2 2 0 002-2v-7a2 2 0 00-2-2h-1V6a4 4 0 00-4-4zm0 2a2 2 0 012 2v2H8V6a2 2 0 012-2zm0 8a1.5 1.5 0 110 3 1.5 1.5 0 010-3z" fill="currentColor" opacity="0.8"/>
                    </svg>
                    <p className="flex-grow text-xs text-amber-800 dark:text-amber-300 font-medium">
                        This screen is defined in code — the composer shows the original layout. Edit the code directly, or duplicate to create an editable copy.
                    </p>
                    <div className="flex items-center gap-2 flex-shrink-0">
                        {onGoToCode && (
                            <button onClick={onGoToCode}
                                className="flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-semibold text-amber-700 dark:text-amber-300 hover:bg-amber-200 dark:hover:bg-amber-800/50 border border-amber-300 dark:border-amber-600 transition-colors">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                Go to Code
                            </button>
                        )}
                        {onDuplicate && (
                            <button onClick={onDuplicate}
                                className="flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-semibold bg-amber-600 hover:bg-amber-700 dark:bg-amber-600 dark:hover:bg-amber-500 text-white transition-colors">
                                <svg viewBox="0 0 16 16" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                                    <rect x="5" y="1" width="9" height="11" rx="1.5"/><rect x="1" y="4" width="9" height="11" rx="1.5" fill="currentColor" opacity="0.2"/>
                                </svg>
                                Duplicate to Edit
                            </button>
                        )}
                    </div>
                </div>
            )}

            {/* ── Keyboard shortcut legend ── */}
            {legendOpen && (
                <div className="flex-none border-b border-primary bg-secondary px-4 py-3">
                    <div className="flex items-center justify-between mb-2.5">
                        <span className="text-[10px] font-bold text-secondary uppercase tracking-widest">Keyboard Shortcuts</span>
                        <button onClick={() => setLegendOpen(false)} className="text-secondary hover:text-primary rounded p-0.5 hover:bg-tertiary-hover">
                            <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 2l8 8M10 2l-8 8"/></svg>
                        </button>
                    </div>
                    <div className="grid grid-cols-3 gap-x-4 gap-y-1.5">
                        {([
                            { keys: ['Tab'],         desc: 'Next widget' },
                            { keys: ['Shift','Tab'], desc: 'Previous widget' },
                            { keys: ['Esc'],         desc: 'Deselect' },
                            { keys: ['Del'],         desc: 'Delete widget' },
                            { keys: ['↑↓←→'],        desc: 'Nudge 1 px' },
                            { keys: ['Shift','↑↓←→'],desc: 'Nudge 10 px' },
                            { keys: ['Ctrl','C'],    desc: 'Copy widget' },
                            { keys: ['Ctrl','V'],    desc: 'Paste (+20 px offset)' },
                            { keys: ['DblClick'],    desc: 'Edit text inline' },
                        ] as { keys: string[]; desc: string }[]).map(({ keys, desc }) => (
                            <div key={desc} className="flex items-center gap-1.5 min-w-0">
                                <div className="flex items-center gap-0.5 flex-shrink-0">
                                    {keys.map((k, i) => (
                                        <React.Fragment key={i}>
                                            {i > 0 && <span className="text-[9px] text-secondary mx-0.5">+</span>}
                                            <kbd className="px-1.5 py-0.5 text-[9px] font-semibold text-gray-700 bg-gray-100 border border-gray-300 rounded dark:bg-gray-700 dark:text-gray-200 dark:border-gray-600 whitespace-nowrap leading-none">{k}</kbd>
                                        </React.Fragment>
                                    ))}
                                </div>
                                <span className="text-[10px] text-secondary truncate">{desc}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* ── Three-panel body ── */}
            <div className={`flex-grow flex min-h-0 overflow-hidden ${isLocked ? 'opacity-60 pointer-events-none select-none' : ''}`}>

                {/* Left: Palette + Layers */}
                <div className="flex-none w-52 border-r border-primary bg-secondary flex flex-col min-h-0">

                    {/* Palette */}
                    <div className="flex-none border-b border-primary overflow-y-auto" style={{ maxHeight: '45%' }}>
                        <div className="flex items-center gap-1.5 px-3 py-2 border-b border-primary sticky top-0 bg-secondary z-10">
                            <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
                                <rect x="1" y="1" width="6" height="6" rx="1"/><rect x="9" y="1" width="6" height="6" rx="1"/>
                                <rect x="1" y="9" width="6" height="6" rx="1"/><rect x="9" y="9" width="6" height="6" rx="1"/>
                            </svg>
                            <span className="text-[10px] font-bold text-secondary uppercase tracking-widest">Palette</span>
                            <span className="ml-auto text-[9px] text-secondary/50">drag → canvas</span>
                        </div>
                        <div className="p-2 space-y-3">
                            {selectedId && selectedWidget && isContainer(selectedWidget) && (
                                <div className="flex items-center gap-1.5 px-2 py-1 rounded bg-accent/10 border border-accent/30 text-[10px] font-semibold text-accent">
                                    <svg viewBox="0 0 12 12" className="w-3 h-3 flex-shrink-0" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><path d="M6 2v8M2 6h8"/></svg>
                                    Click → into <span className="font-mono ml-0.5">{selectedWidget.type}</span>
                                </div>
                            )}
                            {PALETTE_GROUPS.map(group => (
                                <div key={group.label}>
                                    <div className="flex items-center gap-1.5 mb-1.5">
                                        <span className="text-secondary">{group.icon}</span>
                                        <span className="text-[9px] font-bold text-secondary uppercase tracking-widest">{group.label}</span>
                                    </div>
                                    <div className="space-y-1">
                                        {group.types.map(type => (
                                            <div key={type}
                                                draggable
                                                onDragStart={e => { e.dataTransfer.setData('widget-type', type); e.dataTransfer.effectAllowed = 'copy'; }}
                                                onClick={() => handleAddWidget(type)}
                                                className={`flex items-center gap-2 px-2 py-1.5 rounded border text-left
                                                    cursor-grab active:cursor-grabbing select-none transition-all duration-100 ${WIDGET_TILE_COLORS[type]}`}>
                                                <span className={`flex-shrink-0 ${WIDGET_ICON_COLORS[type]}`}>
                                                    {React.cloneElement(WIDGET_ICONS[type] as React.ReactElement, { className: 'w-4 h-4' })}
                                                </span>
                                                <span className="text-xs font-semibold text-primary leading-none">{WIDGET_LABELS[type]}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Layers */}
                    <div className="flex-grow flex flex-col min-h-0 overflow-hidden">
                        <div className="flex items-center gap-1.5 px-3 py-2 border-b border-primary flex-shrink-0 bg-secondary">
                            <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
                                <path d="M2 4h12M2 8h8M2 12h10"/>
                            </svg>
                            <span className="text-[10px] font-bold text-secondary uppercase tracking-widest">Layers</span>
                            <span className="ml-1 text-[9px] text-secondary bg-tertiary px-1.5 py-0.5 rounded-full">{composition.widgets.length}</span>
                            <div className="ml-auto flex items-center gap-0.5">
                                <button onClick={() => setExpandGen(n => n + 1)} title="Expand all"
                                    className="p-0.5 rounded text-secondary hover:text-primary hover:bg-tertiary-hover transition-colors">
                                    <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
                                        <path d="M2 4l4 4 4-4"/><path d="M2 8h8" opacity="0.4"/>
                                    </svg>
                                </button>
                                <button onClick={() => setCollapseGen(n => n + 1)} title="Collapse all"
                                    className="p-0.5 rounded text-secondary hover:text-primary hover:bg-tertiary-hover transition-colors">
                                    <svg viewBox="0 0 12 12" className="w-3 h-3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
                                        <path d="M2 8l4-4 4 4"/><path d="M2 4h8" opacity="0.4"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                        <div className="flex-grow overflow-y-auto p-1.5 space-y-0.5">
                            {composition.widgets.length === 0 && (
                                <p className="text-[10px] text-secondary italic text-center py-4">Drag widgets onto the canvas</p>
                            )}
                            {composition.widgets.map((w, idx) => (
                                <LayerNode key={w.id} widget={w} depth={0}
                                    selectedId={selectedId} onSelect={setSelectedId}
                                    onMoveUp={id => handleMoveWidget(id, 'up')}
                                    onMoveDown={id => handleMoveWidget(id, 'down')}
                                    onDelete={handleDeleteWidget}
                                    isFirst={idx === 0} isLast={idx === composition.widgets.length - 1}
                                    drag={dragState} dragCbs={dragCbs}
                                    collapseGen={collapseGen} expandGen={expandGen} />
                            ))}
                            {dragState.draggingId && (
                                <div
                                    onDragOver={e => { e.preventDefault(); setDragState(prev => ({ ...prev, dropTarget: { id: '__root__', position: 'inside' } })); }}
                                    onDrop={e => { e.preventDefault(); dragCbs.onDrop(); }}
                                    className={`mt-1 mx-1 rounded border border-dashed text-[10px] text-center py-2 transition-all
                                        ${rootDropActive ? 'border-accent text-accent bg-accent/10' : 'border-gray-300 dark:border-gray-600 text-secondary'}`}>
                                    Drop → top level
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Center: WYSIWYG Canvas */}
                <div className="flex-grow flex items-center justify-center bg-slate-950 p-4 overflow-hidden min-w-0">
                    <div
                        ref={canvasRef}
                        className="relative overflow-hidden shadow-2xl shadow-black/60 rounded"
                        style={{
                            aspectRatio: `${composition.gameWidth} / ${composition.gameHeight}`,
                            maxWidth: '100%',
                            maxHeight: '100%',
                            backgroundColor: '#0f172a',
                            backgroundImage: 'linear-gradient(rgba(255,255,255,0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.035) 1px, transparent 1px)',
                            backgroundSize: '40px 40px',
                        }}
                        onDragOver={handleCanvasDragOver}
                        onDragLeave={handleCanvasDragLeave}
                        onDrop={handleCanvasDrop}
                        onClick={() => {
                            setSelectedId(null);
                            if (inlineEditId) handleInlineEditCommit();
                        }}
                    >
                        {/* Drop zone ring */}
                        {canvasDropActive && (
                            <div className="absolute inset-0 ring-2 ring-accent ring-inset bg-accent/5 pointer-events-none z-30 rounded" />
                        )}

                        {/* Empty state */}
                        {composition.widgets.length === 0 && !canvasDropActive && (
                            <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 pointer-events-none select-none">
                                <svg viewBox="0 0 48 48" className="w-12 h-12 text-slate-600" fill="none">
                                    <rect x="4" y="4" width="40" height="40" rx="4" stroke="currentColor" strokeWidth="2" strokeDasharray="5 4"/>
                                    <path d="M24 16v16M16 24h16" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                                </svg>
                                <span className="text-sm text-slate-500 font-medium">Drag a widget from the palette</span>
                                <span className="text-xs text-slate-600">or click a palette tile to add at the default position</span>
                            </div>
                        )}

                        <CanvasCtx.Provider value={canvasCtx}>
                            {composition.widgets.map(widget => (
                                <CanvasWidget key={widget.id} widget={widget} isTopLevel />
                            ))}
                        </CanvasCtx.Provider>
                    </div>
                </div>

                {/* Right: Properties */}
                <div className="flex-none w-64 border-l border-primary bg-secondary flex flex-col min-h-0 overflow-hidden">
                    <div className="flex items-center gap-2 px-3 py-2 border-b border-primary flex-shrink-0">
                        <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none" stroke="currentColor" strokeWidth="1.5">
                            <rect x="1" y="1" width="14" height="14" rx="2"/>
                            <path d="M4 6h5M4 10h8" strokeLinecap="round" opacity="0.6"/>
                        </svg>
                        <span className="text-[10px] font-bold text-secondary uppercase tracking-widest">Properties</span>
                        {selectedWidget && (
                            <span className={`ml-auto text-[10px] font-semibold ${WIDGET_ICON_COLORS[selectedWidget.type]}`}>
                                {selectedWidget.type}
                            </span>
                        )}
                    </div>
                    <div className="flex-grow overflow-y-auto">
                        <PropertiesPanel
                            widget={selectedWidget}
                            composition={composition}
                            onUpdateWidget={handleUpdateWidget}
                            onUpdateComposition={onCompositionChange}
                            screenName={screenName}
                            onRenameScreen={onRenameScreen}
                        />
                    </div>
                </div>
            </div>

            {/* ── Generated Code ── */}
            {codeOpen && (
                <div className="flex-none border-t border-primary bg-secondary flex flex-col" style={{ height: 210 }}>
                    <div className="flex items-center gap-2 justify-between px-3 py-2 border-b border-primary flex-shrink-0">
                        <div className="flex items-center gap-2">
                            <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-secondary" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                                <path d="M5 4L1 8l4 4M11 4l4 4-4 4M9 2l-2 12"/>
                            </svg>
                            <span className="text-xs font-bold text-secondary">Generated Code</span>
                        </div>
                        <CodeActionButtons code={generatedCode} size="sm" />
                    </div>
                    <pre className="flex-grow overflow-auto p-3 text-xs font-mono text-primary bg-primary leading-relaxed">
                        {generatedCode}
                    </pre>
                </div>
            )}
        </div>
    );
};

export default ScreenLayoutComposer;
